version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-bot
    env_file: .env
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:11.3-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
