version: '3'

services:
  database:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-database
    env_file: .env
    depends_on:
      - postgres

  bot:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-bot
    env_file: .env
    restart: always
    depends_on:
      - postgres
      - database

  submitter:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-submitter
    env_file: .env
    restart: always
    depends_on:
      - postgres
      - database

  postgres:
    image: postgres:latest
    env_file: .env
    restart: unless-stopped
