version: "3"

services:

  postgres:
    image: postgres:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - 5432:5432
    
  app:
    build: .
    env_file: .env
    depends_on:
      - postgres
